#数据库： overseas_chinese_artifacts
spring:
  datasource:
    url: "jdbc:mysql://47.96.152.190:3306/overseas_chinese_artifacts?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: '!software2303'
  neo4j:
    uri: bolt://10.4.17.244:7687
    authentication:
      username: neo4j
      password: password123

mybatis:
  mapper-locations: classpath*:com/mapper/*.xml
  type-aliases-package: com.mapper

server:
  port: 8085
